apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: storage-equipment-webapi
  namespace: wac-hospital
spec:
  image: filipskrabak/storage-equipment-webapi
  interval: 1m0s