apiVersion: apps/v1
kind: Deployment
metadata:
  name: steq-storage-equipment-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /steq-openapi
            - name: BASE_URL
              value: /steq-openapi-ui