apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
- name: filipskrabak/storage-equipment-ufe
  newName: filipskrabak/storage-equipment-ufe # {"$imagepolicy":  "wac-hospital:storage-equipment-ufe:name"}
  newTag: main # {"$imagepolicy": "wac-hospital:storage-equipment-ufe:tag"}