apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: steq-ambulance-ufe-content
spec:
  microFrontend: steq-ambulance-ufe
  element: steq-orders-list
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?steq-ambulance-wl(/.*)?$"