apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: steq-storage-equipment-ufe-content
spec:
  microFrontend: steq-storage-equipment-ufe
  element: steq-app
  attributes:
    - name: api-base
      value: /steq-api
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?steq-storage-equipment(/.*)?$"